### ISSUE TITLE
Prevent bringing Unity window to front during upload

### ISSUE THREAD

**Issue by enitimeago** [anatawa12/ContinuousAvatarUploader#13]
Normally when an avatar build completes, the Unity window will be brought to front and take focus.

This is fine for building a single avatar, but is undesirable behavior when uploading multiple avatars in the background.

**Comment by anatawa12** [comment]
It looks bringing Unity to front is cased by VRCSDK and It looks will be fixed in VRCSDK 3.3.0.

**Comment by anatawa12** [comment]
Fixed in 0.2.0 with upgrading VRCSDK to 3.3.0
