### ISSUE TITLE
プログレスバーが欲しい

### ISSUE THREAD

**Issue by wwr-alliance** [anatawa12/ContinuousAvatarUploader#32]
正常に動いているか心配になる事があるので、現在の進捗状況を確認できるプログレスバーが欲しいです。
作業がどの段階なのか（ビルドしている/アップロードしている等）の情報表示もあるとより安心できます。

**Comment by anatawa12** [comment]
たしかにあったほうが良さそうですね。

memo: https://docs.unity3d.com/ScriptReference/EditorGUI.ProgressBar.html (EditorGUILayoutにはなし)
