### ISSUE TITLE
readmeの目的語の記載をちゃんとする

### ISSUE THREAD

**Issue by mecaota** [anatawa12/ContinuousAvatarUploader#34]
いくつか、記載が中途半端になっていて、分かる人でもわかりにくい状態になってる気がしたので、気になった箇所を起票します

https://github.com/anatawa12/ContinuousAvatarUploader/blob/master/README.ja.md

## アバターを設定する の項

> どちらを作成する場合もProjectウィンドウ内で右クリックからCreate/Avatar DescriptorまたはCreate/Avatar Descriptor Groupを選択してください。

((ここにどの画面で何とAvatarを紐付けるのか記載が無い))

> Avatar Descriptorの場合はSet Avatarの欄にHierarchyからアバターをドラック&ドロップしてそのAvatar Descriptorに紐付けてください。

当該箇所に「作成されたasset(descripter)を選択して、Inspector画面からアバターの設定を行ってください」といった記述が無いと、どこで設定するのかが不明確な気がしました(これに5分くらい悩んだ)

## アップロードする の項

> 2.Avatar DescriptorまたはAvatar Descriptor Groupを指定します。Groupを指定した場合、そのグループの中のすべてのアバターがアップロードされます。 Avatar Descriptor Groupの中の各アバターをAvatar Descriptorに指定することもできます。

「`Avatar Descriptor` なら `Avatar Settings` へ、`Avatar Descriptor Group` なら `Groups` へ、DescriptorをD&Dしてください」といった旨の説明はあってよいかなと思います。

あと、

> Avatar Descriptor Groupの中の各アバターをAvatar Descriptorに指定することもできます。

この記述がありましたが、これの意味がいまいちわかりませんでした。 Avatar Descriptor Groupの中に指定済のものもAvatar Descriptorに指定していいという話なのか、そもそもAvatar Descriptor Groupの中の設定項目の一部をAvatar Descriptorとして指定できるという話なのかがわかりません。そのあたりの記述増やしてもいいかもです。

**Comment by anatawa12** [comment]
色々修正したので一旦closeします。ありがとうございます
