### ISSUE TITLE
複数のアバターを一括で登録する機能

### ISSUE THREAD

**Issue by mekanyanko** [anatawa12/ContinuousAvatarUploader#49]
複数のアバターを一括で登録する機能がほしいと思いました。
こちらで改修できるかは余裕があれば見てみようと思いますが、現在、最大で80体ほどを一括アップロードしており、
このときに対象アバターを毎回手でセットしてチェックを入れる作業が大変過ぎたのでHierarchy空複数選択してリストにドラッグしたらまとめてセットされるような機能があると本当に助かります。
また、Windowsだけにチェックを入れることがほとんどなので、一括でチェックを入れる機能もあると助かります。

**Comment by anatawa12** [comment]
Related #1
