### ISSUE TITLE
プレハブをそのままアップする対応があると便利かも

### ISSUE THREAD

**Issue by bdunderscore** [anatawa12/ContinuousAvatarUploader#5]
現在、ContinuousAvatarUploaderはアセットからシーンへ引用することでアバターを設定していますが、プレハブアセットを引用したほうがUnityの基本操作上わかりやすい気がします（アセット→シーンへの引用が普通あまり見かけないので）

**Comment by anatawa12** [comment]
機能提案ありがとうございます。 40f483a21ec5cedb83077035f6995b80974f0f91 で実装しました。
