### ISSUE TITLE
UploadGroupのアセットを選択してからInspectorに内容が表示されるまでに時間がかかりすぎる

### ISSUE THREAD

**Issue by mekanyanko** [anatawa12/ContinuousAvatarUploader#50]
UploadGroupのアセットにアップロード対象として80体前後のアバターをセットした場合に、
ProjectWindowでUploadGroupのアセットを選択してからInspectorに内容が表示されるまでに30秒弱かかることがありました。
内部で複雑な処理をしているなら仕方がないかもしれませんが、手動で1体ずつセットしていることもあり、かなりしんどいと思っています。

**Comment by mekanyanko** [comment]
Inspectorをデバッグモードにすると重くならない事に気づいたので念のため補足しておきます。

**Comment by anatawa12** [comment]
2022で今80程度追加して試した感じ再現できなかったのでどのような設定してるか等教えていただきたいです

**Comment by anatawa12** [comment]
100近くに数を増やしたら再現しました
