### ISSUE TITLE
Errors occur with SDK 3.6.0 from changes to `VRC.Core.API.SetOnlineMode`

### ISSUE THREAD

**Issue by BurnerWah** [anatawa12/ContinuousAvatarUploader#62]
Relevant code: https://github.com/anatawa12/ContinuousAvatarUploader/blob/master/Editor/ContinuousAvatarUploader.cs#L302

When loading a project with SDK 3.6.0, I got put into safe mode because of an error with the usage of `SetOnlineMode`. It seems like the method signature has changed between versions.
![Unity_u8iHTyJxou](https://github.com/anatawa12/ContinuousAvatarUploader/assets/10004812/69038adc-44f4-42a0-9533-a54fb36788fe)

Changing the line to do `API.SetOnlineMode(true);` worked to resolve the error, but I haven't tested to see if it can upload things yet.

Found on Unity 2022.3.6f1

**Comment by anatawa12** [comment]
It looks the API was changed between 3.6.0 beta.1 and 3.6.0. I'll release patch soon

**Comment by anatawa12** [comment]
I have released patch as [0.3.1](https://github.com/anatawa12/ContinuousAvatarUploader/compare/v0.3.0...v0.3.1)
