### ISSUE TITLE
IOS support as target

### ISSUE THREAD

**Issue by Spokeek** [anatawa12/ContinuousAvatarUploader#70]
Now that the SDK allows us to build for IOS platforms, i guess adding it to the target list can be nice to push all the versions of our avatars at once.

**Comment by anatawa12** [comment]
I forget iOS supportness is related to this project. sorry.

basically we can use same avatar as android platform for iOS upload so it might be good to share upload checkbox I think. Could you let me know how do you think?

I think we should have separated setting for versioning system.

**Comment by Spokeek** [comment]
I would say that's a separate entry anyway as you have to switch the field in the SDK and maybe change some specifics.
I don't know if that's the case but we could have a avatar size limitation that is different between android and IOS.

I would say it's better to have a separate option for this.
